### ISSUE TITLE
Undefined name 'finalStatus' in eventHandlers.py

### ISSUE THREAD

**Issue by cclauss** [IBM/quickcd#1]
[flake8](http://flake8.pycqa.org) testing of https://github.com/IBM/quickcd on Python 3.7.0

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./examples/iks/eventHandlers.py:124:17: F821 undefined name 'finalStatus'
                finalStatus
                ^
1     F821 undefined name 'finalStatus'
1
```

**Comment by rchernobelskiy** [comment]
thanks, fixed
